services:
  ms-iam:
    image: ms-iam.api
    container_name: ms-iam
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080"
    env_file:
      - .env
    networks:
      - sg-services-network

networks:
  sg-services-network:
    external: true